[workspace]

[package]
name = "shellrs"
version = "0.1.0"
authors = ["me"]
edition = "2021"
rust-version = "1.80"

[dependencies]
is_executable = "1.0.4"
thiserror = "2.0.11"
levenshtein = { path = "levenshtein" }
rand = "0.9.0"
